.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. Zioncoin_qt test_Zioncoin_qt
clean: FORCE
	$(MAKE) -C .. Zioncoin_qt_clean test_Zioncoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_Zioncoin_qt_check
Zioncoin-qt Zioncoin-qt.exe: FORCE
	 $(MAKE) -C .. Zioncoin_qt
